-- MySQL Script generated by MySQL Workbench
-- 05/29/16 15:31:51
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `test_lab_sivancehnko_zzz_com_ua` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `test_lab_sivancehnko_zzz_com_ua` DEFAULT CHARACTER SET utf8 ;
USE `test_lab_sivancehnko_zzz_com_ua` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test_lab_sivancehnko_zzz_com_ua`.`users` (
  `first_name` VARCHAR(100) NULL,
  `last_name` VARCHAR(100) NULL,
  `email` VARCHAR(100) NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` ENUM('F', 'PM') NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test_lab_sivancehnko_zzz_com_ua`.`project` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NULL,
  `description` VARCHAR(2000) NULL,
  `dedline` DATE NULL,
  `cost` FLOAT NULL,
  `status` ENUM('N', 'A', 'F') NULL DEFAULT 'N',
  `owner` INT NOT NULL,
  `implementer` INT NULL,
  `reit` TINYINT(100) NULL,
  expected_rait tinyint(100) null,
  PRIMARY KEY (`id`),
  INDEX `fk_project_users1_idx` (`owner` ASC),
  INDEX `fk_project_users2_idx` (`implementer` ASC),
  CONSTRAINT `fk_project_users1`
    FOREIGN KEY (`owner`)
    REFERENCES `test_lab_sivancehnko_zzz_com_ua`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_project_users2`
    FOREIGN KEY (`implementer`)
    REFERENCES `test_lab_sivancehnko_zzz_com_ua`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`bids`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test_lab_sivancehnko_zzz_com_ua`.`bids` (
  `user_id` INT NOT NULL,
  `project_id` INT NOT NULL,
  `token` MEDIUMTEXT NULL,
  PRIMARY KEY (`user_id`, `project_id`),
  INDEX `fk_bids_project1_idx` (`project_id` ASC),
  CONSTRAINT `fk_bids_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `test_lab_sivancehnko_zzz_com_ua`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bids_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `test_lab_sivancehnko_zzz_com_ua`.`project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test_lab_sivancehnko_zzz_com_ua`.`tags` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`project_tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test_lab_sivancehnko_zzz_com_ua`.`project_tags` (
  `project_id` INT NOT NULL,
  `tag_id` INT NOT NULL,
  PRIMARY KEY (`project_id`, `tag_id`),
  INDEX `fk_project_tags_tags1_idx` (`tag_id` ASC),
  CONSTRAINT `fk_project_tags_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `test_lab_sivancehnko_zzz_com_ua`.`project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_project_tags_tags1`
    FOREIGN KEY (`tag_id`)
    REFERENCES `test_lab_sivancehnko_zzz_com_ua`.`tags` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

ALTER TABLE `test_lab_sivancehnko_zzz_com_ua`.`users` AUTO_INCREMENT = 1;
ALTER TABLE `test_lab_sivancehnko_zzz_com_ua`.`project` AUTO_INCREMENT = 1;
ALTER TABLE `test_lab_sivancehnko_zzz_com_ua`.`tags` AUTO_INCREMENT = 1;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
