INSERT INTO `mydb`.`project` (`name`, `description`,  `cost`, `status`, `owner`,expected_rait,dedline) 
VALUES 
('Software developer - User interface for real-life game enterprise', 'We are a Berlin-based non-tech start-up. We organise live escape games for groups of 2-6 people who need to solve puzzles in order to escape from a room. We watch the games via webcams and control video & audio in the room from our control room. What we need is a user interface for our game masters which allows them to effectively follow the webcam and send clue texts and pictures to the screen in the game room. An idea of what this interface might look like including its key features can be sent in PowerPoint format upon request.The ideal candidate will have a track record in programming software, possibly in the context of surveillance or game industry.We look forward to your application!',  '150', 'N', '1',13,'2016-06-10'),
('Want to hire internet marketer for my online project, contact me if you are ready for this job', 'Want to hire internet marketer for my online project, contact me if you are ready for this job',  '150', 'N', '1',2,'2017-06-10'),
('App Developer Needed for Fantasy Sports based App', 'I need someone to program and develop an app that will be loading in data from an api, allowing users to create accounts and set up leagues and track and place selections throughout the week as part of game play. ',  '3455', 'N', '1',45,'2016-08-10'),
('Perform state-space modal analysis in Octave/Matlab', 'Perform modal analysis to simulate the application of multiple tuned mass dampers (TMDs) on a structure.

All the parameters of the relevant vibration modes are given for the structure without TMDs. The parameters of the sinusoidal forcing functions representing the dynamic actions on the structure are also given.

Since the TMDs introduce important viscous damping at specifics locations, state-space analysis should be used. The problem should be well represented by a small number of degrees of freedom.

The steps and output of the present project consists in the following:

- the available data for input of the analysis consists in: a) the vibration frequency and mode shape at the points where TMDs will be installed - which are results from a previous FEM analysis. b) The TMD parameters. The 1st step is thus to prepare the available data for input in state-space modal analysis.

 

- formulation of the problem according to modal analysis theory for the structure with TMDs, see attached document;

- write fully commented Octave/Matlab code in order to calculate:

i) modal parameters of the structure with TMDs;

ii) maximum displacement and acceleration of the structure with TMDs due to application of a sinusoidal forcing function;

iii) maximum relative displacement of the TMD masses (in regard to the displacement of the structure where the TMD is located).

- the analysis shall be performed for 8 different sets of modal structural parameters. For each set of modal parameters you will need to input the data, run the analysis and summarize the results in a document.

- write a small report to explain and complement the Matlab code in order to make clear all the theoretical assumptions and analysis steps, showing intermediate numerical results for one of the 8 cases.

All the materials supplied by us or resulting from the execution of the project should remain confidential.',  '10', 'N', '1',1,'2019-06-10'),
('Logo design', 'I would like a logo to be designed.

This is for a bar called "***" inspired by the Marvel character.

The bar interior colours will be themed Black and red.',  '3423', 'N', '1',20,'2016-06-10'),
('LOGO CREATIVE DESIGNER', 'We are developing a new retail and wholesale online shop, for eco-friendly clothing (baby clothes, fitness wear, women wear, etc). We need a creative designer to design our brand logo. 

If you also have experience in designing images for social media and fashion adv for our website content, we could also use you for other projects.',  '4555', 'N', '1',100,'2016-06-10'),
('Partnership for Web Designers', 'Right now, my agency is offering 50% recurring commissions for any SEO client referral. This is going to be very lucrative for you considering we charge most of our clients between $1,000 to $2,000 per month. In this case, you would be pocketing an extra $500-$1000 per month. This added service will end up making you way more money than you are currently making with website design.',  '244', 'N', '1',76,'2016-06-10'),
('Mobile Application Developer', 'looking to hire mobile developers to work with me in comming projects, IOS and Android on phone and tablets applications.',  '455', 'N', '1',8,'2016-06-10'),
('Create a real estate website with chat and bidding function in english and German', 'requirements and application details can be discussed later, work relationship can be extended based on performance to long relationship as am starting my own business and looking for hiring people.',  '344', 'N', '1',45,'2016-06-10'),
('SENIOR FLASH DEVELOPER', 'looking to hire mobile developers to work with me in comming projects, IOS and Android on phone and tablets applications.',  '5456', 'N', '1',100,'2016-06-10'),
('Proofreading & Editing Service', 'I need a professional real estate website and 2 landing pages',  '155560', 'N', '1',3,'2016-06-10'),
('Business Development Director for the freight/trucking industry', 'The ideal candidate will be also an independent person with a problem solving attitude and propositive about solutions on this plugin development.',  '150', 'N', '1',100,'2016-06-10'),
('Simple SQL statement creation (no querying)', 'We are searching for a mechanical engineer / industrial enginneer to design a unique custom made non motorized canine treadmill.',  '150', 'N', '1',100,'2016-06-10'),
('Alter an existing menu for a Store in Asia', 'We pay based on value, nothing else.',  '150', 'N', '1',56,'2016-06-10'),
('Marketing Internship In New Delhi Region At Certination INC. Certination INC.', 'Posiblidad de montar una Starup si se está interesado',  '150', 'N', '1',3,'2016-06-10'),
('Real Estate Flyer Design', 'Who are your favorite film directors, fiction writers, painters, philosophers…?',  '150', 'N', '1',65,'2016-06-10'),
('Seeking illustrator for 10-page childrens book, storyboard/all ready to go', 'Serían con paquetes de trabajos puntuales (2/3 semanas) con flexibilidad horaria',  '150', 'N', '1',100,'2016-06-10'),
('Data entry, Customer Service', 'We are dedicated to developing and producing quality films based on original stories and the masterpieces of world literature',  '150', 'N', '1',67,'2016-06-10'),
('Arabic Speaking Sales Agent for a Very Easy Website Builder', 'Please only apply if you are serious - meaning you work hard, meet deadlines, are teachable, and get things done',  '150', 'N', '1',6,'2016-06-10'),
('American Account Manager', 'We need someone or a company to design and develop our web site, we will provide you with a detailed description of what we need for our site. Once you review all the information please send us your proposal. ',  '150', 'N', '1',100,'2016-06-10'),
('Elastix Configuration', 'We are looking for native English speakers to provide bilingual proofreading for Russian to English language pair.',  '150', 'N', '1',87,'2016-06-10'),
('Clone of jeetle.in with mlm features', 'Please only apply if you are serious - meaning you work hard, meet deadlines, are teachable, and get things done. ',  '150', 'N', '1',100,'2016-06-10'),
('Landing Page Designer', 'We are searching for a mechanical engineer / industrial enginneer to design a unique custom made non motorized canine treadmill.',  '150', 'N', '1',45,'2016-06-10'),
('architect and 3d Designer', 'I am looking for someone to develop a time/gps tracking application to manage my employees.',  '150', 'N', '1',34,'2016-06-10'),
('IMMEDIATE NEED: AN AMERICAN ACCOUNT MANAGER', 'Please only apply if you are serious - meaning you work hard, meet deadlines, are teachable, and get things done. ',  '150', 'N', '1',33,'2016-06-10'),
('Gestion Educativa', 'Turn a rough cartoon sketch of a school mascot into a scalable, coloured and professional graphic design that could be used on posters, web pages, printed items and t-shits... The mascot is a Gang Gang - a type of Australian parrot and is coloured black and red. The sketch has the parrot waering a school whirt (white) with red lettering with the name of our school. ',  '150', 'N', '1',100,'2016-06-10'),
('Solr specialist needed', 'We only take winners. Do you want to win?',  '150', 'N', '1',44,'2016-06-10'),
('LOOKING FOR A NATIVE ENGLISH GRAMMAR WRITER', 'Ideally, we can hire you full time as we continue to grow and scale.',  '7655', 'N', '1',56,'2016-06-10'),
('Website Designer/Builder', 'I am currently searching for a Customer support to represent my gallery and work virtually for the gallery. Biding freelancers should have an excellent customer service and must be outcome-oriented.',  '150', 'N', '1',100,'2016-06-10'),
('Contract Copywriter Needed!', 'The ideal candidate will be also an independent person with a problem solving attitude and propositive about solutions on this plugin development.',  '150', 'N', '1',100,'2016-06-10'),
('Convert Mockup Design to a Wordpress Theme', 'We pay based on value, nothing else.',  '150.4565', 'N', '1',3,'2016-06-10'),
('Web Developer For Multi Level User Platform Needed In Syracuse, NY', 'Ideally, we can hire you full time as we continue to grow and scale.',  '450', 'N', '1',2,'2016-06-10'),
('Videographer in the USA', 'We are dedicated to developing and producing quality films based on original stories and the masterpieces of world literature',  '150', 'N', '1',65,'2016-06-10'),
('Trustworthy Professional Author Needed', 'We only take winners. Do you want to win?',  '1504345', 'N', '1',54,'2016-06-10'),
('website graphic design', 'The gallery needs an assistant that will help manage its data entry, customer, Ed services, reply to emails, handle data processing and also handle all that deals with invoicing and recordings, creating and design website.',  '550', 'N', '1',23,'2016-06-10'),
('WEB DEVELOPER', 'Hello this is a university level project. I am willing to pay up to $200(10,000 - 13,300 Indian Rupees) for this project and I will be needing it by the 20th-25th of May 2016. Below are the details:So it is an optical character recognition application for smartphones which will allow you to recharge the account of your phone without inserting each numbers by yourself. ',  '150', 'N', '1',100,'2016-06-10'),
('Looking for a News Writer: CRE and Retail', 'The ideal candidate will be also an independent person with a problem solving attitude and propositive about solutions on this plugin development.',  '150', 'N', '1',99,'2016-06-10'),
('Business to Business Appointment Setters', 'We only take winners. Do you want to win?',  '150', 'N', '1',89,'2016-06-10'),
('Prestashop Developer', 'I am looking for someone to develop a time/gps tracking application to manage my employees.',  '150', 'N', '1',100,'2016-06-10'),
('Deleting of Duplicate PDFs', 'knowledge of Multitrans Web Editor is an advantage but not mandatory as long as you are familiar with other CAT-tools',  '150', 'N', '1',100,'2016-06-10'),
('Content Writer/Copy Writer Freelancer/Work From Home', 'Ideally, we can hire you full time as we continue to grow and scale.',  '150', 'N', '1',3,'2016-06-10'),
('Stop Motion Save the Date Video', 'I need a professional real estate website and 2 landing pages',  '150', 'N', '1',2,'2016-06-10'),
('Medical Writer Freelancer/Work From Home', 'This is an ongoing project.',  '15', 'N', '1',100,'2016-06-10'),
('Wordpress plugin development', 'We are dedicated to developing and producing quality films based on original stories and the masterpieces of world literature',  '150', 'N', '1',78,'2016-06-10'),
('MARKETTING', 'We are looking for native English speakers to provide bilingual proofreading for Russian to English language pair.',  '150', 'N', '1',66,'2016-06-10'),
('APPLICATION DEVELOPMENT', 'apply website branding on new purchased theme rather than the default theme',  '150', 'N', '1',45,'2016-06-10'),
('Website', 'Healthcare Center is in need of persons qualify for the below listed vacancies;  Data Entry,Customer Service, Sales and Marketing, Typing/Writing. Applicants must be fluent in English language.',  '150', 'N', '1',100,'2016-06-10'),
('Customer service', 'I need to track my employees, and more specifically their time, location, mileage etc...',  '10', 'N', '1',46,'2016-06-10'),
('Logo Designer', 'The gallery needs an assistant that will help manage its data entry, customer, Ed services, reply to emails, handle data processing and also handle all that deals with invoicing and recordings, creating and design website.',  '150', 'N', '1',100,'2016-06-10'),
('Digital Marketer (Tripadvisor and Google)', 'We are looking for an energetic sales agent to promote our online product mainly in Arab Market.',  '150', 'N', '1',43,'2016-06-10'),
('Programmer / Web Developer', 'We are dedicated to developing and producing quality films based on original stories and the masterpieces of world literature',  '150', 'N', '1',100,'2016-06-10'),
('Web Product manager - TheDJList.com', 'We are a global company offering an easy-to-use website builder used by numerous customers around the world. ',  '150', 'N', '1',78,'2016-06-10'),
('Dating articles for blog', 'apply website branding on new purchased theme rather than the default theme',  '0', 'N', '1',100,'2016-06-10'),
('Platform', 'I am currently searching for a Customer support to represent my gallery and work virtually for the gallery. Biding freelancers should have an excellent customer service and must be outcome-oriented.',  '150', 'N', '1',100,'2016-06-10'),
('Recharge your account with only two clicks! (OCR system)', 'Please only apply if you are serious - meaning you work hard, meet deadlines, are teachable, and get things done. ',  '150', 'N', '1',100,'2016-06-10'),
('Mascot design', 'his position will start at 20 hrs / week. Ideally, we can hire you full time as we continue to grow and scale.',  '150', 'N', '1',44,'2016-06-10'),
('Digital analytics expert', 'We are dedicated to developing and producing quality films based on original stories and the masterpieces of world literature',  '150', 'N', '1',56,'2016-06-10'),
('FishEye Correction in C#', 'apply website branding on new purchased theme rather than the default theme',  '150', 'N', '1',100,'2016-06-10'),
('Website Content Administrator', 'Healthcare Center is in need of persons qualify for the below listed vacancies;  Data Entry,Customer Service, Sales and Marketing, Typing/Writing. Applicants must be fluent in English language.',  '150', 'N', '1',100,'2016-06-10'),
('Creating an Online Presentation design either on prezi, video scribe, flash or any similar software.', '',  '789', 'N', '1',35,'2016-06-10'),
('Front-end Web Page Designer in HTML', 'The following will just be a sample of what we need you to lead',  '99', 'N', '1',47,'2016-06-10'),
('PAYROLL ASSISTANT.', 'We are searching for a mechanical engineer / industrial enginneer to design a unique custom made non motorized canine treadmill.',  '150', 'N', '1',34,'2016-06-10'),
('Android & iOS Developer', 'existing prestashop website needs some enhancments and bug fixing for the below requirements',  '150', 'N', '1',33,'2016-06-10'),
('Data Cleansing Expert', 'I need a professional real estate website and 2 landing pages',  '150', 'N', '1',56,'2016-06-10'),
('MSQL / API DEVELOPER', 'Who are your favorite film directors, fiction writers, painters, philosophers…?',  '150', 'N', '1',37,'2016-06-10'),
('python code fix', 'We are dedicated to developing and producing quality films based on original stories and the masterpieces of world literature',  '150', 'N', '1',54,'2016-06-10'),
('Traductions EN -> FR : termes et conditions', 'I will need you to make this character (a tiger) your own, draw the actual 10-page book (medium to be discussed), and make the book print ready as soon as possible. I am ready to go to print immediately upon completion of these pages; already have printer lined up and waiting.',  '150', 'N', '1',78,'2016-06-10'),
('Need to development of voice recognition applications (speaker recognition applications ) on C#.Net.', '',  '999', 'N', '1',56,'2016-06-10'),
('Seeking Business Development Manager', 'Have logo, character, website and storyboard completed and ready to go. A friend drew a character based on my logo, as well as a rather detailed story board for book one for me.',  '150', 'N', '1',100,'2016-06-10'),
('Logo Designer', 'I am looking for someone to develop a time/gps tracking application to manage my employees.',  '150', 'N', '1',100,'2016-06-10'),
('Home Loan Website Content', 'We are looking for native English speakers to provide bilingual proofreading for Russian to English language pair.',  '150', 'N', '1',100,'2016-06-10'),
('need programmer', 'We need someone or a company to design and develop our web site, we will provide you with a detailed description of what we need for our site. Once you review all the information please send us your proposal. ',  '150', 'N', '1',66,'2016-06-10'),
('Web development & design', 'This position is on a contract basis. Expected duration is 4 months. Work will be performed on site in the AM only (8 AM-1 PM) initially.',  '150', 'N', '1',100,'2016-06-10'),
('Post-production for music videos', 'We need aggressive Business to Business Appointment Setters who will actively source new business opportunities through cold calling.',  '150', 'N', '1',100,'2016-06-10'),
('Data leads-zoominfo data-- some one has pro account from zoominfo', 'I am looking for someone who loves to draw and is devoted to the project long term if possible. My heart is fully dedicated to this project. A long term goal is to make the series of books into a cartoon (I have a background in television and teaching). I am hard working and no nonsense. I am looking for the same thing in an illustrator.',  '150', 'N', '1',34,'2016-06-10'),
('Native English speaking proofreaders needed ASAP', 'There are 15 drawings I would like made, as well as the front and back covers, inside flaps, a holding page for my website (a teaser to let them know the book is coming - so that the style is consistent); as well as a few ancillary materials to go on the website to offer for free to children (like bookmarks, and uncolored pages from the book for the kids to download for free from my website and color themselves). (After this I will also make an e-book version and an ipad applciation based on the book (s).) ',  '150', 'N', '1',100,'2016-06-10'),
('Treadmill designer', 'We are expanding our engineering team and are seeking talented software engineers with strong server side C++ development skills, server virtualization experience and a track record of successful commercial software development.',  '150', 'N', '1',45,'2016-06-10'),
('Design a site', 'We are searching for a mechanical engineer / industrial enginneer to design a unique custom made non motorized canine treadmill.',  '150', 'N', '1',100,'2016-06-10'),
('Web site designer/programmer', 'Have logo, character, website and storyboard completed and ready to go. A friend drew a character based on my logo, as well as a rather detailed story board for book one for me.',  '150', 'N', '1',100,'2016-06-10'),
('Android tacking application', 'Looking for an experienced C# developer for a 1 month project. The work is to develop a fish-eye image correction software based on C#.',  '150', 'N', '1',100,'2016-06-10'),
('Payroll and AP Assistant - Data Entry', 'I will need you to make this character (a tiger) your own, draw the actual 10-page book (medium to be discussed), and make the book print ready as soon as possible. I am ready to go to print immediately upon completion of these pages; already have printer lined up and waiting.',  '150', 'N', '1',99,'2016-06-10'),
('Accounting homework', 'I am looking for someone to write content for roughly 19 pages of content for my mortgage brokerage business.',  '150', 'N', '1',4,'2016-06-10'),
('Data Entry/Customer Service Representative', 'Book a minimum of 10 quality appointments a week',  '150', 'N', '1',66,'2016-06-10'),
('Video Presentation Creator/ Graphic Designer', 'We need b2b news for professional audience. Our main topic is shopping malls, also we are interested in news about commercial real estate, retail brands and stores, retail chains, e-commerce. Each story have to have at least one photo or illustration.  ',  '467', 'N', '1',45,'2016-06-10'),
('Backend Node.Js Developer', 'We need aggressive Business to Business Appointment Setters who will actively source new business opportunities through cold calling.',  '150', 'N', '1',100,'2016-06-10'),
('Front-End Developer', 'I am looking for someone to write content for roughly 19 pages of content for my mortgage brokerage business.',  '150', 'N', '1',67,'2016-06-10'),
('Program that compress a file iusing the algorithm', 'existing prestashop website needs some enhancments and bug fixing for the below requirements',  '150', 'N', '1',45,'2016-06-10'),
('Client services Engineer', 'This position is on a contract basis. Expected duration is 4 months. Work will be performed on site in the AM only (8 AM-1 PM) initially.',  '150', 'N', '1',78,'2016-06-10'),
('Freelance Online trainers', 'We are searching for a mechanical engineer / industrial enginneer to design a unique custom made non motorized canine treadmill.',  '150', 'N', '1',67,'2016-06-10'),
('Mortgage Website Content', 'I am looking for someone to develop a time/gps tracking application to manage my employees.',  '150', 'N', '1',56,'2016-06-10'),
('customize wordpress plugin', 'I need a professional real estate website and 2 landing pages',  '3334', 'N', '1',45,'2016-06-10'),
('Social Media Manager', 'We need someone or a company to design and develop our web site, we will provide you with a detailed description of what we need for our site. Once you review all the information please send us your proposal. ',  '150', 'N', '1',100,'2016-06-10'),
('Blog Writer & SMM for Movie Company', 'We are dedicated to developing and producing quality films based on original stories and the masterpieces of world literature',  '150', 'N', '1',4,'2016-06-10'),
(' NATIV Proofreading (RU/UKR-EN) Proofreading ', 'We are looking for native English speakers to provide bilingual proofreading for Russian to English language pair.',  '150', 'N', '1',78,'2016-06-10'),
('Layout Designer', 'Who are your favorite film directors, fiction writers, painters, philosophers…?',  '555', 'N', '1',2,'2016-06-10'),
('Graphic and Web Designer for Movie Company', 'Aspect Translation Company is looking for experienced freelance-translators in En-Ru language pair to join our translation projects.',  '150', 'N', '1',100,'2016-06-10'),
('Translator (En-Ru, medicine, patents)', 'Embroidered Lace manufacturer looking for lace designer using on bridal/fashion dress Guipure Lace/Tulle Lace:4~8 inches Trims&Motifs: 4~6 inches Price varies by the design

Students are welcome

Looking for long term cooperation relationship!',  '3466', 'N', '1',100,'2016-06-10'),
('Lace Design', 'The target audience would be ladies and men, 28-65 interested organic and/or healthy alternatives to off the shelf self care products.',  '150', 'N', '1',7,'2016-06-10');

INSERT INTO `mydb`.`tags` (`name`) 
VALUES 
('Illustrator'),
('Sales Representation'),
('Network Administrator'),
('Flash Animation'),
('php'),
('Js'),
('Java'),
('C#'),
('Web Analytics'),
('E-Commerce'),
('Graphics Design'),
('Copyediting'),
('Applications Development'),
('Brand design'),
('Software Development'),
('Logo Design'),
('Copywriting'),
('Web Content'),
('Web Development'),
('Information Security'),
('Mobile Application'),
('Data Mining'),
('Client-Server Applications'),
('Translator'),
('IT Expert'),
('Online Marketing'),
('SEO')
;


INSERT INTO `mydb`.`project_tags` (`project_id`,tag_id) 
VALUES 
(24,16),
(80,14),
(52,14),
(24,6),
(51,17),
(33,6),
(3,3),
(10,3),
(62,15),
(95,10),
(57,1),
(91,7),
(75,11),
(56,12),
(22,2),
(2,2),
(90,9),
(27,12),
(15,9),
(22,7),
(85,9),
(47,1),
(35,10),
(21,14),
(14,2),
(51,4),
(11,7),
(96,4),
(40,4),
(17,10),
(54,15),
(45,2),
(20,5),
(6,1),
(65,6),
(89,11),
(12,16),
(76,5),
(60,15),
(54,17),
(11,17),
(69,11),
(43,10),
(64,16),
(93,1),
(13,4),
(15,12),
(30,5),
(40,16),
(37,8),
(57,3),
(19,12),
(48,1),
(12,5),
(92,4),
(48,16),
(58,9),
(55,14),
(25,5),
(42,7),
(60,17),
(53,15),
(10,8),
(22,6),
(59,1),
(7,3),
(56,3),
(53,6),
(95,5),
(96,10),
(88,8),
(42,14),
(77,17),
(8,3),
(93,17),
(62,9),
(46,8),
(1,9),
(44,9),
(66,5),
(94,6),
(67,5),
(73,11),
(94,14),
(8,12),
(40,2),
(32,17),
(1,11),
(94,1),
(52,17),
(63,15),
(46,16),
(29,17),
(32,19),
(74,8),
(37,5),
(23,13),
(14,18),
(94,7);
